apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: karpenter-ec2-default
spec:
  amiFamily: "AL2" # Or "Bottlerocket" if you use Bottlerocket nodes
  role: ${karpenter_node_role_arn} # IAM role ARN for nodes
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/${cluster_name}: owned
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
  tags:
    karpenter.sh/discovery: ${cluster_name}
    Name: "karpenter-ec2-default"
