apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app2
  namespace: ui-app2
  labels:
    app: ui-app2
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ui-app2
  template:
    metadata:
      labels:
        app: ui-app2
        version: v1
    spec:
      containers:
        - name: ui-app2
          image: 154697348611.dkr.ecr.eu-west-1.amazonaws.com/ui-app2:latest
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "80"