apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: karpenter-ec2-default
spec:
  amiFamily: ${ami_family}
  # Option: use explicit subnet ids or tag-based discovery. If subnet_ids provided, we use them.
  subnetSelectorTerms:
  %{ if length(subnet_ids) > 0 }
  - ids:
%{ for id in subnet_ids ~}
    - ${id}
%{ endfor ~}
  %{ else }
  - tags:
      ${discovery_tag_key}: ${discovery_tag_value}
  %{ endif }
  securityGroupSelectorTerms:
  %{ if length(security_group_ids) > 0 }
  - ids:
%{ for id in security_group_ids ~}
    - ${id}
%{ endfor ~}
  %{ else }
  - tags:
      kubernetes.io/cluster/${cluster_name}: owned
  %{ endif }
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
  tags:
    karpenter.sh/discovery: ${discovery_tag_value}