apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: karpenter-ec2-default
spec:
  amiFamily: {{ .Values.amiFamily }}
  subnetSelectorTerms:
    {{- if .Values.subnetIds }}
    - ids:
        {{- range .Values.subnetIds }}
        - {{ . }}
        {{- end }}
    {{- else }}
    - tags:
        {{ .Values.discoveryTagKey }}: {{ .Values.discoveryTagValue }}
    {{- end }}
  securityGroupSelectorTerms:
    {{- if .Values.securityGroupIds }}
    - ids:
        {{- range .Values.securityGroupIds }}
        - {{ . }}
        {{- end }}
    {{- else }}
    - tags:
        kubernetes.io/cluster/{{ .Values.clusterName }}: owned
    {{- end }}
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
  tags:
    karpenter.sh/discovery: {{ .Values.discoveryTagValue }}