apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-app1-ingress
  namespace: ui-app1
  labels:
    app: ui-app1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: app1.cloudcraftlab.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-app1-service
                port:
                  number: 80